name: "Build & Release"   # You can name it as you want

on: push

jobs:  # Telling what jobs we need to happen
  build:      # Specify the building name and machine
    name: Build & Release  # you can name the build whatever you want
    runs-on: macos-latest # here we selected macos-latest to be able to get ios build
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: pubspec.yaml # path to pubspec.yaml
      - run: flutter pub get
      - run: flutter test
      - run: flutter build apk --release
      - run: flutter build appbundle --release
      - name: Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          prerelease: true
          files: |
            build/app/outputs/apk/roll_feathers-${{ github.ref_name }}-release.apk
            build/app/outputs/bundle/roll_feathers-${{ github.ref_name }}-release.aab
